### ISSUE TITLE
Beacon Control App issue

### ISSUE THREAD

**Issue by rsanni** [upnext/BeaconControl_Android_sample_app#3]
Hi,

I have installed the beacon control sample app and tried to trigger the url actions via application page by assigning a zone with beacon devices, when i open the beacon control app it crashes and shows error as unfortunately app has been stopped.

Kindly suggest me a solution for this.

My Log shows as 

06-12 04:42:43.901 19445-19445/io.upnext.beaconcontrol.app E/AndroidRuntime: FATAL EXCEPTION: main Process: io.upnext.beaconcontrol.app, PID: 19445                                                                             java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.removeAll(java.util.Collection)' on a null object reference at io.upnext.beaconcontrol.sdk.backend.service.BeaconServiceHelper.removeUnsupportedRangesFromTriggers(BeaconServiceHelper.java:116) at io.upnext.beaconcontrol.sdk.backend.service.BeaconServiceHelper.handleUnsupportedProtocols(BeaconServiceHelper.java:91) at io.upnext.beaconcontrol.sdk.backend.service.BeaconServiceHelper.access$000(BeaconServiceHelper.java:30) at io.upnext.beaconcontrol.sdk.backend.service.BeaconServiceHelper$1.onSuccess(BeaconServiceHelper.java:65) at io.upnext.beaconcontrol.sdk.backend.service.BeaconServiceHelper$1.onSuccess(BeaconServiceHelper.java:62) at io.upnext.beaconcontrol.sdk.backend.mediator.HttpCallMediator.notifyOnSuccess(HttpCallMediator.java:62) at io.upnext.beaconcontrol.sdk.backend.mediator.HttpCallMediator.access$100(HttpCallMediator.java:23) at io.upnext.beaconcontrol.sdk.backend.mediator.HttpCallMediator$1.onSuccess(HttpCallMediator.java:97) at io.upnext.beaconcontrol.sdk.backend.BeaconControlCallback.onResponse(BeaconControlCallback.java:20) at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:7303) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Minty123** [comment]
Hi Rsanni,
How do you run the app? On an emulator or a real device? And if so, which version of Android do you run it on? How far can you get in the app?
I can only log in and once I'm on the beacon tab, the app crashes. However, I have different error msgs in my log...
Greetings!

**Comment by rsanni** [comment]
Hi @Minty123 
I have run the app by using the real device ,
version of android is 6.01 and API level is 23.
It crashes when the app starts to scan the beacon device only when action via ZoneTrigger, For BeaconTrigger app doesn't crashed.

Regards,
Rajeswaran Sanniyasi.
